improve configure's checks for libperl and update RELNOTES with instructions on how to compile on debian

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27098,11 +27098,37 @@ echo $ECHO_N "checking for $perlpath >= 5.8.0... $ECHO_C" >&6
 			if test "$PERL_VER" = "yes"; then
 				echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+				echo "$as_me:$LINENO: checking Checking for perl compiler, linker, libraries and headers" >&5
+echo $ECHO_N "checking Checking for perl compiler, linker, libraries and headers... $ECHO_C" >&6
+	    			PERL_CC=`$perlpath -MConfig -e 'print $Config{cc},"\n";'`
+			    	PERL_LD=`$perlpath -MConfig -e 'print $Config{ld},"\n";'`
+
+				rm -f testperl$ac_exeext testperl.$ac_objext testperl.c testperl.err
+	    			cat > testperl.c <<EOF
+#include "EXTERN.h"
+#include "perl.h"
+#include "XSUB.h"
+int main () { (void)&perl_construct; return 0; }
+EOF
+				$PERL_CC $PERL_CFLAGS -c testperl.c >testperl.err 2>&1 &&
+	   	 		$PERL_LD -o testperl testperl.o $PERL_LDFLAGS >testperl.err 2>&1 &&
+	    			test -x testperl &&
+	    			have_perl=yes
+				if test "$have_perl" = "yes"; then
+					echo "$as_me:$LINENO: result: ok" >&5
+echo "${ECHO_T}ok" >&6
 
 cat >>confdefs.h <<_ACEOF
 #define USE_PERL 1
 _ACEOF
 
+				else
+					PERL_LDFLAGS=""
+					PERL_CFLAGS=""
+					{ { echo "$as_me:$LINENO: error: Failed try ./configure --disable-perl" >&5
+echo "$as_me: error: Failed try ./configure --disable-perl" >&2;}
+   { (exit 1); exit 1; }; }
+				fi
 			else
 				echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -27217,7 +27243,7 @@ do
 	fi
 done
 if test "x$CCDV" = "x" ; then
-	${CC-cc} $DEFS $CPPFLAGS $CFLAGS "ccdv.c" -o "ccdv" >/dev/null 2>&1
+	${CC-cc} $DEFS $CPPFLAGS $CFLAGS "autotools/ccdv.c" -o "ccdv" >/dev/null 2>&1
 	strip ./ccdv >/dev/null 2>&1
 	./ccdv >/dev/null 2>&1
 	if test $? -eq 96 ; then
@@ -27284,10 +27310,13 @@ unset wi_resolved_path wi_path
 	wi_cv_path_ccdv="$CCDV"
 	CC="$CCDV $CC"	# trailing space needed
 	USECCDV="#"
+	echo "$as_me:$LINENO: result: $ccdv" >&5
+echo "${ECHO_T}$ccdv" >&6
 else
 	wi_cv_path_ccdv=""
 	USECCDV=""
-
+	echo "$as_me:$LINENO: result: \"Not Found\"" >&5
+echo "${ECHO_T}\"Not Found\"" >&6
 fi
 
 fi
