change configure error on perl to point to RELNOTES

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27125,8 +27125,8 @@ _ACEOF
 				else
 					PERL_LDFLAGS=""
 					PERL_CFLAGS=""
-					{ { echo "$as_me:$LINENO: error: Failed try ./configure --disable-perl" >&5
-echo "$as_me: error: Failed try ./configure --disable-perl" >&2;}
+					{ { echo "$as_me:$LINENO: error: Failed. See the RELNOTES file" >&5
+echo "$as_me: error: Failed. See the RELNOTES file" >&2;}
    { (exit 1); exit 1; }; }
 				fi
 			else
