updated configure to fail if a user doesn't specify a IRCD

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3528,6 +3528,25 @@ else
 echo "${ECHO_T}no" >&6
 
 fi;
+echo "$as_me:$LINENO: checking A compatible IRCD is specified" >&5
+echo $ECHO_N "checking A compatible IRCD is specified... $ECHO_C" >&6
+case "$IRCD_FILES_SRC" in
+   "Ultimate.c")
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	;;
+   "Unreal.c")
+	echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	;;
+  *)
+	{ { echo "$as_me:$LINENO: error: 'You must define a IRCD to use. See ./configure --help for more information'" >&5
+echo "$as_me: error: 'You must define a IRCD to use. See ./configure --help for more information'" >&2;}
+   { (exit 1); exit 1; }; }
+	;;
+esac
+
+
 echo "$as_me:$LINENO: checking What type of Authentication to use..." >&5
 echo $ECHO_N "checking What type of Authentication to use...... $ECHO_C" >&6
 # Check whether --enable-auth or --disable-auth was given.
